name: Lint

on:
  push:
    branches: [main]
    paths: ["**.lua"]
  pull_request:
    paths: ["**.lua"]

jobs:
  stylua:
    name: Lint with stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
