name: Test

on:
  push:
    branches: [main]
    paths: ["**.lua"]
  pull_request:
    paths: ["**.lua"]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        nvim-versions: ["v0.12.0", "nightly"]
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luassert
        run: luarocks --lua-version 5.1 install luassert

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: Run tests
        run: make test
